# Application bindings
bind = SUPER_SHIFT, A, exec, wofi --show drun --style ~/.config/theme/generated/wofi.css
bind = SUPER_SHIFT, S, exec, copyq show
bind = SUPER_SHIFT, D, exec, ghostty -e tmux attach
bind = SUPER_SHIFT, F, exec, vivaldi

bind = SUPER_SHIFT, Q, exec, export XDG_CURRENT_DESKTOP=GNOME && gnome-control-center
bind = SUPER_SHIFT, E, exec, bash -c 'if tmux list-clients -t R_ 2>/dev/null | grep -q .; then tmux detach-client -s R_; else kitty -1 --title=R_ -e tmux new-session -AD -s R_; fi'
bind = SUPER_SHIFT, R, exec, bash -c 'if tmux list-clients -t R_ 2>/dev/null | grep -q .; then tmux detach-client -s R_; else git -C ~/notes pull & alacritty --title R_ -e tmux new-session -AD -s R_; fi'
bind = SUPER_SHIFT, T, exec, nautilus -w ~/Downloads/

bind = SUPER_SHIFT, Z, exec, bash -c 'hyprshot -m region --freeze --clipboard-only && wl-paste | tesseract - - | wl-copy'
bind = SUPER_SHIFT, X, exec, hyprshot -m region --clipboard-only --freeze
bind = SUPER_SHIFT, B, exec, alacritty --title popup_ -e bluetui
bind = SUPER_SHIFT, J, exec, bash /home/jon/ssh-chat.sh
bind = SUPER_SHIFT, N, exec, bash /home/jon/.ssh/vpn/connect.sh


bind = SUPER CONTROL, space, togglefloating

bind = ALT, Tab, cyclenext
bind = SHIFT ALT, Tab, cyclenext, prev
bind = SUPER, Tab, workspace,previous

bind = SUPER, space, exec, wl-kbptr -o modes=tile,bisect

bind = SUPER CONTROL, Q, killactive
bind = SUPER CONTROL, W, exec, bash ~/.config/hypr/setup-monitors.sh
bind = SUPER CONTROL, E, exec, swaync-client -t
bind = SUPER CONTROL, R, exec, bash ~/.config/theme/apply-theme.sh
bind = SUPER CONTROL, T, exec, hyprlock

bindel = SUPER CONTROL, Z, exec, brightnessctl -e4 -n1 set 10%-
bindel = SUPER CONTROL, X, exec, brightnessctl -e4 -n1 set 10%+

bindel = SUPER CONTROL, A, exec, bash ~/.config/hypr/scripts/volume-snap.sh down
bindel = SUPER CONTROL, S, exec, bash ~/.config/hypr/scripts/volume-snap.sh up
bind = SUPER CONTROL, F, fullscreen, 0
bind = SUPER CONTROL, G, exec, bash ~/.config/hypr/scripts/audio-output.sh

bindl = SUPER CONTROL, V, exec, playerctl play-pause
bindl = SUPER CONTROL, B, exec, playerctl next
bindl = SUPER CONTROL, N, exec, playerctl previous

bind = SUPER CONTROL, Y, exec, systemctl suspend-then-hibernate
bind = SUPER CONTROL, H, submap, resize
bindd = SUPER CONTROL, M, Toggle split, togglesplit, # dwindle
bindel = SUPER CONTROL, I, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
bindel = SUPER CONTROL, O, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
submap = resize
binde = , l, resizeactive, 100 0
binde = , h, resizeactive, -100 0
binde = , k, resizeactive, 0 -100
binde = , j, resizeactive, 0 100
bind = , q, submap, reset
bind = , escape, submap, reset
submap = reset

bindm = SUPER, mouse:272, movewindow # left click
bindm = SUPER, mouse:273, resizewindow # right click
