#!/usr/bin/env bash
# Generated by apply-theme.sh — do not edit directly
cd "$(tmux display-message -p -F '#{pane_current_path}')" 2>/dev/null || exit 0
git rev-parse --is-inside-work-tree &>/dev/null || exit 0

branch=$(git symbolic-ref --short HEAD 2>/dev/null || git rev-parse --short HEAD 2>/dev/null)
text="$branch"

yellow="{{color3}}"
red="{{color1}}"
bg="{{base}}"
fg="{{foreground}}"
accent="{{git_color}}"
accent_fg="{{base}}"

if [[ -n $(git status -s 2>/dev/null) ]]; then
  dirty=$(git status --porcelain 2>/dev/null | wc -l | tr -d ' ')
  text+=" #[fg=${yellow}]*${dirty}"
fi

if git rev-parse --abbrev-ref @{u} &>/dev/null; then
  behind=$(git rev-list --count HEAD..@{u} 2>/dev/null)
  ahead=$(git rev-list --count @{u}..HEAD 2>/dev/null)
  if [[ $behind -gt 0 ]]; then
    text+=" #[fg=${red}]${behind}"
  fi
  if [[ $ahead -gt 0 ]]; then
    text+=" #[fg=${red}]${ahead}"
  fi
fi

echo "#[fg=${accent},bg=${bg},nobold,nounderscore,noitalics]█#[fg=${accent_fg},bg=${accent},nobold,nounderscore,noitalics]󰘬 #[fg=${fg},bg=${bg}] ${text}#[fg=${bg},bg=${bg},nobold,nounderscore,noitalics]█"
