-- Generated by apply-theme.sh — do not edit directly
return {
	normal = {
		a = { fg = "{{background}}", bg = "{{lualine_normal}}", gui = "bold" },
		b = { fg = "{{lualine_text}}", bg = "{{lualine_bg}}" },
		c = { fg = "{{lualine_text}}", bg = "{{background}}" },
	},
	insert = { a = { fg = "{{background}}", bg = "{{lualine_insert}}", gui = "bold" } },
	visual = { a = { fg = "{{background}}", bg = "{{lualine_visual}}", gui = "bold" } },
	replace = { a = { fg = "{{background}}", bg = "{{lualine_replace}}", gui = "bold" } },
	inactive = {
		a = { fg = "{{lualine_inactive}}", bg = "{{background}}", gui = "bold" },
		b = { fg = "{{lualine_inactive}}", bg = "{{background}}" },
		c = { fg = "{{lualine_inactive}}", bg = "{{background}}" },
	},
}
