# Generated by apply-theme.sh — do not edit directly
set -g @catppuccin_flavour '{{flavour}}'
set -g @catppuccin_status_modules_left "session"

set -g @catppuccin_window_right_separator "█"
set -g @catppuccin_window_left_separator " █"
set -g @catppuccin_window_number_position "right"
set -g @catppuccin_window_middle_separator " | "

set -g @catppuccin_window_default_text "#{?window_zoomed_flag,#[fg={{sapphire}}] #[fg=default],}#{b:pane_current_path}"
set -g @catppuccin_window_current_text "#[fg={{base}}]#{?window_zoomed_flag,#[fg=#1d4ed8] #[fg={{base}}],}#{b:pane_current_path}"

set -g @catppuccin_window_status_enable "no"
set -g @catppuccin_window_default_fill "none"
set -g @catppuccin_window_current_fill "all"

set -g @catppuccin_application_color "{{surface1}}"
set -g @catppuccin_application_icon "󰜎"
set -g @catppuccin_status_modules_right "application"
set -g @catppuccin_status_left_separator "█"
set -g @catppuccin_status_right_separator "█"
