# Generated by apply-theme.sh — do not edit directly
set -g @catppuccin_flavour '{{flavour}}'
set -g @catppuccin_status_modules_left "session"

set -g @catppuccin_window_right_separator "█"
set -g @catppuccin_window_left_separator " █"
set -g @catppuccin_window_number_position "right"
set -g @catppuccin_window_middle_separator " | "

#  
set -g @catppuccin_window_default_text "#{?window_zoomed_flag,#[fg=#1e66f5#,bold] #[default],}#{b:pane_current_path}"
set -g @catppuccin_window_current_text "#[fg={{base}}]#{?window_zoomed_flag,#[fg=#1e66f5#,bold] #[fg={{base}}#,nobold],}#{b:pane_current_path}"

set -g @catppuccin_window_status_enable "no"
set -g @catppuccin_window_default_fill "none"
set -g @catppuccin_window_current_fill "all"

set -g @catppuccin_application_color "{{surface1}}"
set -g @catppuccin_application_icon "󰜎"
set -g @catppuccin_status_modules_right "application"
set -g @catppuccin_status_left_separator "█"
set -g @catppuccin_status_right_separator "█"

# Dim inactive panes to highlight the active one
set -g window-style 'bg={{pane_inactive}}'
set -g window-active-style 'bg={{background}}'

# copy-mode → tinta bg SOLO del pane activo en modo (detectar copy-mode).
# re-evaluar en cada cambio de modo Y de pane activo (window-active-style es
# nivel-window); si el activo no esta en modo, cae al global de arriba.
set-hook -g pane-mode-changed 'if-shell -F "#{pane_in_mode}" "set -w window-active-style bg={{copy_mode_bg}}" "set -uw window-active-style"'
set-hook -g after-select-pane 'if-shell -F "#{pane_in_mode}" "set -w window-active-style bg={{copy_mode_bg}}" "set -uw window-active-style"'
