/* Generated by apply-theme.sh — do not edit directly */
* {
	font-family: "Hack", monospace;
}

window {
	background-color: transparent;
}

#input {
	margin: 5px;
  border: 1px {{surface2}};
  border-style: solid;
	background-color: {{background}};
	border-radius: 10px;
	color: {{foreground}};
  outline-color: {{background}};

}

#input:focus {
  box-shadow: rgba(239, 159, 118, 0.4) 0px 0px 0px 2px, rgba(239, 159, 118, 0.65) 0px 4px 6px -1px, rgba(239, 159, 118, 0.08) 0px 1px 0px inset;
}

#outer-box {
	margin: 2px;
	padding: 10px;
  border: 1px {{surface2}};
	border-radius: 10px;
  border-style: solid;
	background-color: {{background}};
}

#scroll {
	margin: 5px;
}

#text {
	padding: 4px;
	color: {{foreground}};
}

#entry:nth-child(even){
	background-color: {{surface0}};
}

#entry:selected {
	background-color: {{surface2}};
}

#text:selected {
	background: transparent;
}
