local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not (vim.uv or vim.loop).fs_stat(lazypath) then
  local lazyrepo = "https://github.com/folke/lazy.nvim.git"
  local out = vim.fn.system({ "git", "clone", "--filter=blob:none", "--branch=stable", lazyrepo, lazypath })
  if vim.v.shell_error ~= 0 then
    vim.api.nvim_echo({
      { "Failed to clone lazy.nvim:\n", "ErrorMsg" },
      { out, "WarningMsg" },
      { "\nPress any key to exit..." },
    }, true, {})
    vim.fn.getchar()
    os.exit(1)
  end
end
vim.opt.rtp:prepend(lazypath)

require('options')
require('keymaps')

require("lazy").setup("plugins")

-- Apply the active theme's colorscheme (generated by ~/.config/theme/apply-theme.sh).
-- Lazy loads the matching plugin on demand via the :colorscheme trigger.
local ok, name = pcall(dofile, vim.fn.expand("~/.config/theme/generated/colorscheme.lua"))
vim.cmd.colorscheme((ok and type(name) == "string" and name ~= "" and name) or "catppuccin-mocha")
